services:
  mysql:
    image: mysql:8.0
    container_name: final_boss_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: final
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - final_boss_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
networks:
  default:
    name: dev_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16
          gateway: 172.26.0.1
volumes:
  final_boss_data: